# Generated by Django 3.0.4 on 2020-03-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_auto_20200315_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaseuser',
            name='username',
        ),
    ]
