server:
  port: 8081
logging:
  level:
    org.springframework: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${OKTA_DOMAIN}/oauth2/default
          jwk-set-uri: https://${OKTA_DOMAIN}/oauth2/default/v1/keys
